name: pulse_hear
description: "PulseHear App for Deaf and Hard of Hearing"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.8

dependencies:
  flutter:      
    sdk: flutter
  google_fonts: ^8.0.1
  # بما أن صورك SVG، يجب إضافة هذه المكتبة
  flutter_svg: ^2.0.10+1
  # مكتبة البلوتوث لمهمتك كمطور أول
  flutter_blue_plus: ^1.31.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    # التعديل هنا: أضفنا مجلد images لأن الصور بداخله وبصيغة svg
    - assets/images/logo.svg
    - assets/images/waves.svg

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-VariableFont_wght.ttf
        - asset: assets/fonts/Nunito-Italic-VariableFont_wght.ttf
