name: pulse_hear
description: "PulseHear App for Deaf and Hard of Hearing"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.8

dependencies:
  flutter:      
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # الصور (تأكدي إنك غيرتيها لـ png في المجلد)
  assets:
    - assets/logo.png
    - assets/waves.png

  # الخطوط
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-VariableFont_wght.ttf
        - asset: assets/fonts/Nunito-Italic-VariableFont_wght.ttf
